<?php

$slug = fn (string $value): string => strtolower(trim((string) preg_replace('/[^A-Za-z0-9]+/', '-', $value), '-'));

$product = function (
    string $name,
    string $category,
    string $use,
    int $price,
    ?int $rentalPrice,
    string $unit = 'unit',
    int $stock = 8,
    bool $rentable = true,
    ?string $customSlug = null,
) use ($slug): array {
    return [
        'slug' => $customSlug ?: $slug($name),
        'name' => $name,
        'category' => $category,
        'use' => $use,
        'price' => $price,
        'rental_price_per_day' => $rentable ? $rentalPrice : null,
        'unit' => $unit,
        'stock' => $stock,
        'is_for_sale' => true,
        'is_for_rent' => $rentable,
        'availability_status' => 'available',
        'equipment_condition' => 'Leivant stock review required before dispatch',
    ];
};

$categories = [
    ['name' => 'Hand Tools', 'description' => 'Daily site hand tools for masonry, carpentry, excavation, finishing, and general construction tasks.'],
    ['name' => 'Power Tools', 'description' => 'Powered drilling, cutting, sanding, fastening, and concrete finishing tools for active construction sites.'],
    ['name' => 'Earthmoving & Heavy Machinery', 'description' => 'Heavy equipment for excavation, grading, hauling, loading, trenching, and compaction.'],
    ['name' => 'Concrete & Masonry Equipment', 'description' => 'Concrete mixing, placing, cutting, finishing, and masonry support equipment.'],
    ['name' => 'Lifting & Material Handling', 'description' => 'Cranes, lifts, hoists, trucks, and handling equipment for moving people and materials safely.'],
    ['name' => 'Foundation & Drilling Equipment', 'description' => 'Ground drilling, pile works, rock breaking, and foundation support equipment.'],
    ['name' => 'Surveying & Measuring', 'description' => 'Layout, alignment, angle measurement, positioning, and site calculation instruments.'],
    ['name' => 'Electrical & Power Equipment', 'description' => 'Power generation, lighting, testing, backup power, and temporary site distribution equipment.'],
    ['name' => 'Safety & PPE', 'description' => 'Personal protection, emergency response, fire safety, and visibility gear for construction teams.'],
    ['name' => 'Dewatering Equipment', 'description' => 'Pumps and systems for removing water from excavations, trenches, and active work areas.'],
    ['name' => 'Site Accessories & Consumables', 'description' => 'Scaffolding, barriers, fasteners, storage, welding, sealing, coating, and surface preparation supplies.'],
    ['name' => 'Building Materials', 'description' => 'Core construction materials from mchanga, kokoto, cement, blocks, steel, timber, roofing, and concrete materials.'],
    ['name' => 'Finishing Materials', 'description' => 'Tiles, paint, gypsum, doors, fittings, fixtures, adhesives, grout, and finishing consumables.'],
];

$products = [
    $product('Claw Hammer', 'Hand Tools', 'Driving nails and light demolition work', 35000, 4000, 'item', 24),
    $product('Sledgehammer', 'Hand Tools', 'Breaking concrete, rocks, and heavy site obstructions', 85000, 9000, 'item', 12),
    $product('Chisel Set', 'Hand Tools', 'Cutting and carving concrete, wood, and metal', 55000, 5000, 'set', 18),
    $product('Screwdriver Set', 'Hand Tools', 'Flat and Phillips screw fastening for site installation work', 45000, 4000, 'set', 30),
    $product('Tape Measure 30ft', 'Hand Tools', 'Site measurements, setting out, and quantity checks', 28000, 3000, 'item', 35),
    $product('Spirit Level', 'Hand Tools', 'Checking horizontal and vertical alignment during installation', 48000, 5000, 'item', 20),
    $product('Pliers Set', 'Hand Tools', 'Gripping, bending, and cutting wire', 52000, 5000, 'set', 18),
    $product('Wrench Set', 'Hand Tools', 'Tightening bolts, nuts, fittings, and mechanical connections', 95000, 10000, 'set', 14),
    $product('Hand Saw', 'Hand Tools', 'Manual cutting of timber and light boards', 38000, 4000, 'item', 18),
    $product('Hacksaw', 'Hand Tools', 'Cutting metal pipes, rods, and light sections', 30000, 3000, 'item', 22),
    $product('Masonry Trowel', 'Hand Tools', 'Applying mortar, cement, and masonry bedding', 26000, 3000, 'item', 40),
    $product('Plastering Trowel', 'Hand Tools', 'Finishing walls, ceilings, and plaster surfaces', 32000, 3000, 'item', 35),
    $product('Hawk Board', 'Hand Tools', 'Holding plaster or mortar while finishing surfaces', 42000, 4000, 'item', 16),
    $product('Concrete Float', 'Hand Tools', 'Smoothing concrete surfaces during finishing work', 38000, 4000, 'item', 20),
    $product('Bull Float', 'Hand Tools', 'Leveling large poured concrete areas', 180000, 18000, 'item', 8),
    $product('Digging Bar', 'Hand Tools', 'Breaking hard ground, loosening soil, and trench preparation', 70000, 7000, 'item', 12),
    $product('Pickaxe', 'Hand Tools', 'Digging and breaking compacted soil', 65000, 7000, 'item', 16),
    $product('Shovel / Spade', 'Hand Tools', 'Excavation, backfilling, sand movement, and site cleanup', 42000, 4000, 'item', 40),
    $product('Heavy Duty Wheelbarrow', 'Hand Tools', 'Transporting concrete, sand, blocks, aggregate, and rubble on site', 145000, 12000, 'item', 25, true, 'heavy-duty-wheelbarrow'),
    $product('Caulk Gun', 'Hand Tools', 'Sealing gaps around windows, walls, joints, and finishes', 24000, 2500, 'item', 18),

    $product('Electric Drill', 'Power Tools', 'Drilling holes and driving screws for installation work', 180000, 18000, 'unit', 14),
    $product('Impact Driver', 'Power Tools', 'High-torque screw and bolt driving', 260000, 25000, 'unit', 10),
    $product('Rotary Hammer Drill', 'Power Tools', 'Heavy-duty concrete drilling, anchor fixing, and light demolition', 420000, 30000, 'unit', 8, true, 'rotary-hammer-drill'),
    $product('Circular Saw', 'Power Tools', 'Cutting wood, plywood, boards, and selected metal sections', 320000, 28000, 'unit', 8),
    $product('Professional Angle Grinder', 'Power Tools', 'Cutting and grinding metal, tile, masonry, and site fittings', 180000, 18000, 'item', 18, true, 'professional-angle-grinder'),
    $product('Reciprocating Saw', 'Power Tools', 'Demolition cutting in tight spaces and renovation work', 380000, 30000, 'unit', 6),
    $product('Jigsaw', 'Power Tools', 'Curved and detailed cuts in timber and boards', 220000, 20000, 'unit', 8),
    $product('Belt Sander', 'Power Tools', 'Surface smoothing and finishing work', 280000, 24000, 'unit', 6),
    $product('Concrete Vibrator 38mm', 'Power Tools', 'Removing air bubbles from fresh concrete in slabs, columns, and beams', 690000, 45000, 'unit', 9, true, 'concrete-vibrator-38mm'),
    $product('Power Trowel', 'Power Tools', 'Smoothing large concrete floors after placement', 3600000, 180000, 'unit', 3),
    $product('Bench Grinder', 'Power Tools', 'Sharpening tools and grinding metal components', 420000, 35000, 'unit', 4),
    $product('Nail Gun', 'Power Tools', 'Fast nailing for framing, roofing, and finishing work', 520000, 42000, 'unit', 5),

    $product('Crawler Excavator', 'Earthmoving & Heavy Machinery', 'Digging foundations, trenching, and bulk excavation', 180000000, 950000, 'unit', 2),
    $product('Wheeled Excavator', 'Earthmoving & Heavy Machinery', 'Mobile digging on hard surfaces and urban work areas', 170000000, 900000, 'unit', 2),
    $product('Bulldozer', 'Earthmoving & Heavy Machinery', 'Pushing soil, land clearing, site grading, and formation works', 240000000, 1200000, 'unit', 1),
    $product('Backhoe Loader', 'Earthmoving & Heavy Machinery', 'Combined digging and loading for mixed site operations', 145000000, 750000, 'unit', 2),
    $product('Wheel Loader', 'Earthmoving & Heavy Machinery', 'Moving gravel, soil, debris, aggregate, and loading trucks', 160000000, 850000, 'unit', 2),
    $product('Skid Steer Loader', 'Earthmoving & Heavy Machinery', 'Compact loading and movement in tight construction areas', 95000000, 550000, 'unit', 2),
    $product('Motor Grader', 'Earthmoving & Heavy Machinery', 'Road leveling, grading, and surface preparation', 260000000, 1300000, 'unit', 1),
    $product('Dump Truck', 'Earthmoving & Heavy Machinery', 'Transporting sand, gravel, rubble, and site materials', 120000000, 650000, 'unit', 4),
    $product('Articulated Hauler', 'Earthmoving & Heavy Machinery', 'Off-road heavy material transport for rough terrain', 300000000, 1500000, 'unit', 1),
    $product('Trencher', 'Earthmoving & Heavy Machinery', 'Digging narrow trenches for pipes, cables, and drainage lines', 110000000, 620000, 'unit', 1),
    $product('Compactor / Road Roller', 'Earthmoving & Heavy Machinery', 'Compacting soil, sub-base, and asphalt surfaces', 135000000, 720000, 'unit', 2),
    $product('Plate Compactor', 'Earthmoving & Heavy Machinery', 'Base preparation, paving works, trenches, and small road sections', 2450000, 120000, 'unit', 4, true, 'plate-compactor-honda-engine'),

    $product('Portable Concrete Mixer 350L', 'Concrete & Masonry Equipment', 'Mixing concrete on site for slabs, columns, beams, and block works', 1850000, 85000, 'unit', 6, true, 'portable-concrete-mixer-350l'),
    $product('Concrete Mixer Truck', 'Concrete & Masonry Equipment', 'Delivering ready-mix concrete to active sites', 190000000, 850000, 'unit', 1),
    $product('Concrete Pump', 'Concrete & Masonry Equipment', 'Pumping concrete to elevated or distant placement areas', 150000000, 900000, 'unit', 1),
    $product('Concrete Batch Plant', 'Concrete & Masonry Equipment', 'High-volume on-site concrete production', 450000000, 2500000, 'unit', 1),
    $product('Concrete Cutting Machine', 'Concrete & Masonry Equipment', 'Cutting hardened concrete slabs, joints, and openings', 2800000, 150000, 'unit', 3),
    $product('Concrete Buggy', 'Concrete & Masonry Equipment', 'Transporting concrete across site before placement', 9500000, 220000, 'unit', 2),
    $product('Concrete Hopper', 'Concrete & Masonry Equipment', 'Controlled concrete release from trucks and elevated points', 6500000, 180000, 'unit', 2),
    $product('Concrete Sealer & Applicator', 'Concrete & Masonry Equipment', 'Surface coating and concrete protection work', 420000, 30000, 'set', 5),
    $product('Bump Cutter', 'Concrete & Masonry Equipment', 'Removing high spots and correcting concrete surface levels', 240000, 18000, 'item', 6),
    $product('Concrete Edger', 'Concrete & Masonry Equipment', 'Creating clean rounded slab edges', 35000, 3000, 'item', 20),
    $product('Concrete Groover', 'Concrete & Masonry Equipment', 'Cutting control joints in fresh concrete', 45000, 4000, 'item', 18),

    $product('Tower Crane', 'Lifting & Material Handling', 'Lifting heavy materials on high-rise construction sites', 650000000, 2800000, 'unit', 1),
    $product('Mobile Crane', 'Lifting & Material Handling', 'Flexible heavy lifting from truck-mounted crane equipment', 340000000, 1800000, 'unit', 1),
    $product('Chain Block / Chain Hoist', 'Lifting & Material Handling', 'Manual lifting of heavy loads on site', 420000, 35000, 'unit', 8),
    $product('Forklift', 'Lifting & Material Handling', 'Moving pallets, equipment, and heavy site loads', 85000000, 450000, 'unit', 2),
    $product('Manlift / Boom Lift', 'Lifting & Material Handling', 'Elevated worker access for installation and maintenance', 130000000, 650000, 'unit', 1),
    $product('Scissor Lift', 'Lifting & Material Handling', 'Platform work at height for finishing and installation', 90000000, 500000, 'unit', 1),
    $product('Hand Truck / Dolly', 'Lifting & Material Handling', 'Moving equipment, boxes, and small loads around site', 180000, 15000, 'item', 10),
    $product('Pallet Jack', 'Lifting & Material Handling', 'Moving pallets in storage areas and construction supply zones', 950000, 55000, 'unit', 5),
    $product('Mobile Scaffolding Set', 'Lifting & Material Handling', 'Access scaffolding for plastering, painting, facade repairs, and elevated tasks', 1350000, 65000, 'set', 12, true, 'mobile-scaffolding-set'),
    $product('Extension Ladder 24ft', 'Lifting & Material Handling', 'Roofing, ceiling, painting, electrical, gutter, and maintenance access', 360000, 25000, 'item', 10, true, 'extension-ladder-24ft'),

    $product('Drill Rig', 'Foundation & Drilling Equipment', 'Deep ground drilling for foundation and investigation works', 420000000, 2300000, 'unit', 1),
    $product('Pile Boring Machine', 'Foundation & Drilling Equipment', 'Boring holes for foundation piles', 380000000, 2100000, 'unit', 1),
    $product('Pile Driver', 'Foundation & Drilling Equipment', 'Driving piles into ground for foundation support', 500000000, 2600000, 'unit', 1),
    $product('Rock Breaker', 'Foundation & Drilling Equipment', 'Hydraulic rock and concrete demolition', 65000000, 420000, 'unit', 2),
    $product('Foundation Auger', 'Foundation & Drilling Equipment', 'Drilling foundation holes and post holes', 18500000, 250000, 'unit', 2),

    $product('Laser Level', 'Surveying & Measuring', 'Precise horizontal and vertical alignment', 420000, 30000, 'kit', 8),
    $product('Total Station', 'Surveying & Measuring', 'Accurate surveying, setting out, and site measurement', 10500000, 250000, 'unit', 2),
    $product('Theodolite', 'Surveying & Measuring', 'Angle measurement for layout and surveying control', 6500000, 180000, 'unit', 2),
    $product('Digital Measuring Tape', 'Surveying & Measuring', 'Fast and precise distance measurement on site', 220000, 18000, 'item', 8),
    $product('GPS Survey Equipment', 'Surveying & Measuring', 'Large site positioning and survey coordination', 16000000, 320000, 'kit', 2),
    $product('Construction Calculator', 'Surveying & Measuring', 'On-site material and construction calculations', 180000, 12000, 'item', 10),

    $product('Portable Generator Small', 'Electrical & Power Equipment', 'Power supply for small remote construction tasks', 2100000, 95000, 'unit', 5, true, 'site-generator-5kva'),
    $product('Large Generator', 'Electrical & Power Equipment', 'Full jobsite power supply for larger construction teams', 45000000, 550000, 'unit', 2),
    $product('Light Tower', 'Electrical & Power Equipment', 'Illuminating large areas for night works', 18500000, 280000, 'unit', 3),
    $product('Portable Floodlight', 'Electrical & Power Equipment', 'Targeted site lighting for work zones and security', 280000, 20000, 'item', 12),
    $product('UPS System', 'Electrical & Power Equipment', 'Backup power for critical equipment and site offices', 950000, 45000, 'unit', 4),
    $product('Digital Multimeter', 'Electrical & Power Equipment', 'Electrical testing and diagnostics', 180000, 12000, 'item', 12),
    $product('Voltage Tester', 'Electrical & Power Equipment', 'Detecting live circuits before electrical work', 45000, 4000, 'item', 20),
    $product('Extension Reels / Power Strips', 'Electrical & Power Equipment', 'Temporary power distribution on construction sites', 110000, 9000, 'item', 18),

    $product('Safety Helmet / Hard Hat', 'Safety & PPE', 'Head protection for construction workers', 30000, null, 'item', 60, false),
    $product('Safety Boots Steel Toe', 'Safety & PPE', 'Foot protection for construction and site work', 85000, null, 'pair', 40, false),
    $product('Reflective Safety Vest', 'Safety & PPE', 'Worker visibility on active construction sites', 18000, null, 'item', 100, false),
    $product('Safety Gloves', 'Safety & PPE', 'Hand protection for handling tools, materials, and rough surfaces', 12000, null, 'pair', 100, false),
    $product('Safety Goggles / Face Shield', 'Safety & PPE', 'Eye and face protection for cutting, grinding, and dust work', 35000, null, 'item', 45, false),
    $product('Ear Muffs / Earplugs', 'Safety & PPE', 'Hearing protection around noisy machinery and power tools', 28000, null, 'item', 45, false),
    $product('Dust Mask / Respirator', 'Safety & PPE', 'Respiratory protection during dust and surface preparation work', 22000, null, 'item', 60, false),
    $product('Safety Harness', 'Safety & PPE', 'Fall protection for height work', 180000, 15000, 'item', 12),
    $product('First Aid Kit', 'Safety & PPE', 'On-site emergency care support', 85000, null, 'kit', 20, false),
    $product('Fire Extinguisher', 'Safety & PPE', 'Fire safety support for site offices and work areas', 95000, null, 'unit', 18, false),
    $product('Site Safety Gear Kit', 'Safety & PPE', 'Helmet, vest, gloves, and protection basics for supervised construction sites', 95000, 8000, 'kit', 40, true, 'site-safety-gear-kit'),

    $product('Submersible Pump', 'Dewatering Equipment', 'Pumping water from excavations, pits, and trenches', 1250000, 65000, 'unit', 5),
    $product('Wellpoint System', 'Dewatering Equipment', 'Lowering groundwater levels around excavations', 28000000, 420000, 'system', 1),
    $product('Centrifugal Pump', 'Dewatering Equipment', 'Surface water removal and transfer pumping', 2400000, 95000, 'unit', 4),

    $product('Scaffolding System', 'Site Accessories & Consumables', 'Elevated work platforms for building works and finishing', 3500000, 140000, 'system', 6),
    $product('Safety Barriers / Barricades', 'Site Accessories & Consumables', 'Site access control, hazard marking, and pedestrian separation', 65000, 6000, 'piece', 80),
    $product('Nails, Bolts, Screws Assorted', 'Site Accessories & Consumables', 'Fastening for carpentry, framing, installation, and site repairs', 45000, null, 'pack', 120, false),
    $product('Cement Bags', 'Site Accessories & Consumables', 'Foundation, masonry, plastering, and general concrete works', 18500, null, 'bag', 300, false),
    $product('Welding Machine + Electrodes', 'Site Accessories & Consumables', 'Metal joining, fabrication, and repair works', 850000, 50000, 'set', 4),
    $product('Paint Sprayer', 'Site Accessories & Consumables', 'Surface coating, painting, and finishing work', 650000, 40000, 'unit', 5),
    $product('Caulk / Sealant', 'Site Accessories & Consumables', 'Gap filling, waterproofing, and finishing joints', 18000, null, 'tube', 150, false),
    $product('Sandpaper / Abrasives', 'Site Accessories & Consumables', 'Surface preparation before painting, coating, or finishing', 15000, null, 'pack', 100, false),
    $product('Toolbox / Tool Storage Cabinet', 'Site Accessories & Consumables', 'Tool organization, storage, and secure transport', 280000, 18000, 'unit', 10),

    $product('Mchanga / Building Sand Trip', 'Building Materials', 'Sand for blockwork, plastering, concrete mixing, bedding, and general construction works', 180000, null, 'trip', 80, false, 'mchanga-building-sand-trip'),
    $product('Kokoto / Crushed Aggregate Trip', 'Building Materials', 'Aggregate for concrete, foundation works, slabs, beams, columns, and drainage bedding', 220000, null, 'trip', 70, false, 'kokoto-crushed-aggregate-trip'),
    $product('Concrete Blocks 6 Inch', 'Building Materials', 'Walling blocks for residential, rental, and commercial construction', 1500, null, 'block', 20000, false, 'concrete-blocks-6-inch'),
    $product('Reinforcement Steel Rebar 12mm', 'Building Materials', 'Structural reinforcement for foundations, columns, beams, and slabs', 3200, null, 'kg', 12000, false, 'reinforcement-steel-rebar-12mm'),
    $product('Binding Wire Roll', 'Building Materials', 'Tying reinforcement steel and site fixing works', 65000, null, 'roll', 120, false, 'binding-wire-roll'),
    $product('Roofing Sheets Gauge 28', 'Building Materials', 'Roof covering for residential, rental, and commercial buildings', 26000, null, 'sqm', 3000, false, 'roofing-sheets-gauge-28'),
    $product('Timber Formwork Board', 'Building Materials', 'Formwork, setting out, temporary works, roofing support, and carpentry tasks', 18000, null, 'piece', 600, false, 'timber-formwork-board'),
    $product('Waterproofing Membrane', 'Building Materials', 'Roof slab, wet area, balcony, and foundation moisture protection', 28000, null, 'sqm', 900, false, 'waterproofing-membrane'),

    $product('Floor Tiles Standard', 'Finishing Materials', 'Floor and wall finishing for rooms, kitchens, bathrooms, and circulation areas', 28000, null, 'sqm', 2500, false, 'floor-tiles-standard'),
    $product('Interior Paint 20L', 'Finishing Materials', 'Interior wall and ceiling paint for finishing works', 95000, null, 'bucket', 400, false, 'interior-paint-20l'),
    $product('Gypsum Ceiling Board', 'Finishing Materials', 'Ceiling and interior design works for modern finishes', 22000, null, 'board', 800, false, 'gypsum-ceiling-board'),
    $product('Tile Adhesive Bag', 'Finishing Materials', 'Tile installation adhesive for floors, walls, and wet areas', 24000, null, 'bag', 900, false, 'tile-adhesive-bag'),
    $product('Tile Grout Pack', 'Finishing Materials', 'Joint finishing for tile installations', 12000, null, 'pack', 700, false, 'tile-grout-pack'),
    $product('Plumbing Fixture Set', 'Finishing Materials', 'Bathroom and kitchen plumbing fixtures for finishing and installation', 380000, null, 'set', 80, false, 'plumbing-fixture-set'),
    $product('Electrical Wiring Bundle', 'Finishing Materials', 'Electrical wiring and installation materials for residential construction', 260000, null, 'bundle', 120, false, 'electrical-wiring-bundle'),
];

return [
    'categories' => array_map(fn (array $category): array => array_merge($category, ['slug' => $slug($category['name'])]), $categories),
    'products' => $products,
];
